# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
# syntax=docker/dockerfile:1

# Build stage
FROM node:lts-alpine AS builder
WORKDIR /app

# Install dependencies and build the app
COPY package.json package-lock.json tsconfig.json ./
COPY src ./src
RUN npm ci \
    && npm run build

# Runner stage
FROM node:lts-alpine AS runner
WORKDIR /app

# Copy build and dependencies
COPY --from=builder /app/build ./build
COPY --from=builder /app/node_modules ./node_modules

ENV NODE_ENV=production

# Start the MCP server via stdio
CMD ["node", "build/index.js"]
